### PR TITLE
Use security-context@3.

### PR DESCRIPTION
**Pull request by mattcollier**
node and karma tests are passing locally.

@davidlehn are there any webpack config changes required here?

### CODE REVIEW

**Comment by davidlehn** [comment]
@mattcollier re webpack, it looks like the output is pulling in the security-context dist/module.js file correctly, so I don't think any changes are needed.

**Comment by davidlehn** [comment]
I just noticed the browserify tests failed.  That is unfortunate.  Might be tricky to fix.

**Comment by davidlehn** [comment]
Easiest browserify fix was to use esmify.  Unsure if we need to document that trick or not.

**Comment by mattcollier** [comment]
Just diff'd the context files against what is on master in this repo and they are identical.  Proceeding with merge.

**Pull request merged**
