### PR TITLE
Allow sign/verify with BitcoinSignature2016

### PR DESCRIPTION
**Pull request by harlantwood**
This is in support of work that @aquabu and I have been doing with on signing JSON-LD with bitcoin private keys, in conjunction with @ChristopherA and @msporny.

Some impl notes:
- Refactor verification (DRY up) existing and new verification functions
- Use CoMakery/bitcore-message (browserified) as bower version currently fails

There are a few pending tests that I want to finish; submitting this now to get feedback, if any.

### CODE REVIEW

**Comment by harlantwood** [comment]
BTW for those interested, you can see an early version of this code in a fork of the JSON-LD playground (click the "Signed" tab) here: http://peaceful-inlet-31266.herokuapp.com/playground/

**Comment by dlongley** [comment]
Thanks @harlantwood!

You said there were a few tests that you wanted to finish... are you done with that now? Is this ready for full review and to merge from your perspective?

**Comment by dlongley** [comment]
@harlantwood,

I've rebased your changes onto master and done some minor refactoring on this dev branch:

https://github.com/digitalbazaar/jsonld-signatures/tree/CoMakery-btc-sign

If you'd like to add more tests before I pull this in, you can rebase your work off of that branch. Otherwise, I can pull this in now and you can add more tests later in a separate PR. What's your preference?

**Comment by harlantwood** [comment]
Thanks @dlongley!  Please go ahead and merge it in.  The pending tests are the promise API; we didn't touch the promise side of the code so they should go easily.

**Comment by dlongley** [comment]
Landed as d2c96175d24c673ea6fbd25bb34b4e5a453b07c7.

**Comment by harlantwood** [comment]
Nice

**Pull request closed without merging**
