### PR TITLE
Fix signer param in LinkedDataSignature constructor.

### LINKED ISSUE #136: Ensure LinkedDataSignature constructor initializes this.signer
Subclasses (like the 2020 suite) sometimes pass a `signer` object to the suite constructor, instead of a key.
Make sure that gets initialized in the constructor (this is currently not working).

### PR DESCRIPTION
**Pull request by mattcollier**
Fixes #136.

### CODE REVIEW

**Comment by mattcollier** [comment]
@dmitrizagidulin now it's the case that if one passes in a `signer` without a `verificationMethod`, a proof with a `verificationMethod` of `undefined` is produced. Parameter validation is needed to prevent this from happening.

I'm wondering what the relationship between the `signer`, `verificationMethod` and `key` parameters should be.

Is it the case that if a `signer` is specified a `verificationMethod` must also be specified **OR** a `key` is specified.  Which is to say, one may not pass in all three?

https://github.com/digitalbazaar/jsonld-signatures/blob/3f7be0f82e6e4f7bf0c1b33209a6b257e2f75765/lib/suites/LinkedDataSignature.js#L31-L52

**Comment by dlongley** [comment]
I thought it used to be the case that `signer` included an `id` property that would be used in the `verificationMethod` field. Has that changed?

**Review by dlongley — APPROVED** [review]

**Comment by dmitrizagidulin** [comment]
@dlongley 
> I thought it used to be the case that signer included an id property that would be used in the verificationMethod field. Has that changed?

The closest thing to that would be  https://github.com/digitalbazaar/ed25519-signature-2020/blob/main/lib/Ed25519Signature2020.js#L44, which uses the `key`'s id, but not the signer's.
We can modify it to also use the signer's.

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Comment by dmitrizagidulin** [comment]
@mattcollier @dlongley - I've added this logic here: https://github.com/digitalbazaar/jsonld-signatures/pull/138

**Pull request merged**
