### PR TITLE
Infrastructure

### PR DESCRIPTION
**Pull request by harlantwood**
Minor tweaks; most notably adding linting to CI

- run linting and code checks in CI
- code fixes requested by jshint
- update node modules
- remove unused package and script
- add node 7 to CI
- gitignore .idea dir

### CODE REVIEW

**Comment by msporny** [comment]
Hey @harlantwood, I'm seeing PR #13, #14, #16, and #17. My assumption is that the PRs should be applied in that order? Could you fix the conflicts for #13 (this issue) and then I can pull that in?

**Comment by harlantwood** [comment]
Yes, exactly.  @msporny please merge in that order.  I've fixed all conflicts I believe.

**Comment by harlantwood** [comment]
[bump]

**Comment by harlantwood** [comment]
Bumping... please merge these PRs @msporny or @dlongley 👍

**Pull request merged**
