### PR TITLE
Add jsdoc lint rules.

### PR DESCRIPTION
**Pull request by aljones15**
A lot of jsdoc in this repo, but the jsdoc rules are not enabled so added them.
Did not fix any of the docs itself as my other task kind of requires it.

### CODE REVIEW

**Comment by davidlehn** [comment]
Rebased and updated to recent dependencies.  *Lots* of warnings to address.

**Comment by davidlehn** [comment]
Is this still needed?  8.x has some jsdoc lint updates.

**Comment by msporny** [comment]
@aljones15 is this PR needed any more? If not, can we close it?

**Comment by aljones15** [comment]
closing as this is old and no one is going to have time to update this much jsdoc any time soon.

**Pull request closed without merging**
