### PR TITLE
Allow `expansionMap` overrides.

### PR DESCRIPTION
**Pull request by davidlehn**
Fixes https://github.com/digitalbazaar/jsonld-signatures/issues/111.

Unsure where to add tests, (see https://github.com/digitalbazaar/jsonld-signatures/issues/146).

### CODE REVIEW

**Review by dlongley — APPROVED** [review]

**Comment by davidlehn** [comment]
@dlongley I had bad logic in there the first pass. This is better. It looks like lower level handles `false` but maybe converting to `undefined` is better.

**Review by dlongley — APPROVED** [review]
Clearly a test here would be ideal as you note. Maybe the test could involve using some data with an undefined term and an expansion map that sets a flag and always throws -- then assert the flag has been set. Something simple and quick in the local test suite here.

**Comment by davidlehn** [comment]
@dlongley Can non-trivial tests even be written in this module at the moment?  Previously the suites were here that ran the tests.  Probably some mock code is needed just to even make tests possible.  The code is indirectly tested through the suites, but that's not ideal to test common features.

**Comment by dmitrizagidulin** [comment]
@davidlehn @dlongley in this particular PR, the expansionMap logic in `add()` and `verify()` could be tested via unit tests, by sinon-mocking the `suite` param.

**Pull request merged**
